import { LineItem, BankingDetails, FleetUnit, ClientRecord, QuoteDocument, InvoiceDocument, RfqLead } from './types';

export const DEFAULT_CATALOG_ITEMS: Omit<LineItem, 'id' | 'total'>[] = [
  {
    description: 'VIP Mobile Restroom Trailer (Dual Private Cubicles, Porcelain Flush, Solar Light, Basins)',
    category: 'Sanitation',
    quantity: 1,
    unit: 'Weekend Hire (Thu - Sun)',
    unitPrice: 3800,
  },
  {
    description: 'Mobile Cold-Room Trailer (Hygienic Chiller -2°C to +4°C, Meat Rail, 220V Mains / Gen Input)',
    category: 'Cold-Chain',
    quantity: 1,
    unit: 'Weekend Hire (Thu - Sun)',
    unitPrice: 3500,
  },
  {
    description: 'Waterproof Stretch Tent (Heavy-Duty Bedouin, Weather-Resistant, Setup & Rigging included)',
    category: 'Tents',
    quantity: 1,
    unit: 'Event Duration',
    unitPrice: 4500,
  },
  {
    description: 'High-Back Executive VIP Chairs & Memorial Seating (Per 100 Chairs)',
    category: 'Tents',
    quantity: 1,
    unit: 'Bundle of 100',
    unitPrice: 1200,
  },
  {
    description: 'Active PA Sound Reinforcement System + 2x UHF Wireless Mics + Sound Engineer on-site',
    category: 'Sound',
    quantity: 1,
    unit: 'Service Day',
    unitPrice: 2800,
  },
  {
    description: 'Low-Noise 7.5kVA Standby Backup Generator (AVR Regulated, Full Fuel Tank)',
    category: 'Sound',
    quantity: 1,
    unit: 'Event Duration',
    unitPrice: 1500,
  },
  {
    description: 'Ceremonial Livestock: Prime Slaughter Ox / Cattle (Inspected, Healthy, Limpopo Farm Sourced)',
    category: 'Livestock',
    quantity: 1,
    unit: 'Head',
    unitPrice: 16500,
  },
  {
    description: 'Ceremonial Livestock: Indigenous Boer Goat (Live weight ~35-45kg, Ritual Ready)',
    category: 'Livestock',
    quantity: 1,
    unit: 'Head',
    unitPrice: 2600,
  },
  {
    description: 'Doorstep Livestock Trailer Delivery & Offloading (Greater Tzaneen / Mopani Region)',
    category: 'Transport',
    quantity: 1,
    unit: 'Trip',
    unitPrice: 850,
  },
  {
    description: 'Commercial Pre- & Post-Event Janitorial Cleanup & Waste Bagging Support',
    category: 'Cleaning',
    quantity: 1,
    unit: 'Day Service',
    unitPrice: 1800,
  },
  {
    description: 'Fleet Delivery, Towing & Site Rigging Surcharge (Per km outside Tzaneen 30km radius)',
    category: 'Transport',
    quantity: 1,
    unit: 'Per km',
    unitPrice: 14,
  },
];

export const DEFAULT_BANKING_DETAILS: BankingDetails = {
  bankName: 'First National Bank (FNB)',
  accountHolder: 'HLUGISO (PTY) LTD',
  accountNumber: '62849102847',
  branchCode: '250655',
  accountType: 'Corporate Cheque Account',
  referenceFormat: 'Invoice Number or Client Surname',
};

export const DEFAULT_FLEET_UNITS: FleetUnit[] = [
  {
    id: 'fleet-1',
    name: 'Mobile Cold-Room Trailer #1',
    type: 'cold_room',
    registrationOrCode: 'HLU-MCR-01',
    capacityOrSpecs: '-2°C to +4°C • Single Axle • 220V/Gen • 2x Meat Rails',
    status: 'booked',
    assignedLocation: 'Nkowankowa Section B',
    assignedClient: 'Mabotja Family Memorial',
    bookingDates: 'Thu 12 Sep – Sun 15 Sep',
    notes: 'Pre-trip sanitize completed. Pickup Thursday 14:00.',
  },
  {
    id: 'fleet-2',
    name: 'Mobile Cold-Room Trailer #2',
    type: 'cold_room',
    registrationOrCode: 'HLU-MCR-02',
    capacityOrSpecs: '-2°C to +4°C • Heavy-Duty Double Axle • Full Meat Rails',
    status: 'available',
    assignedLocation: 'Tzaneen Base Depot',
    notes: 'Ready for deployment.',
  },
  {
    id: 'fleet-3',
    name: 'VIP Mobile Restroom Trailer #1',
    type: 'vip_toilet',
    registrationOrCode: 'HLU-VIP-01',
    capacityOrSpecs: 'Dual Cubicle (His/Hers) • Porcelain Flush • Solar Lights • Basins',
    status: 'booked',
    assignedLocation: 'Lenyenye Zone 2',
    assignedClient: 'Khosa Funeral Service',
    bookingDates: 'Fri 13 Sep – Sun 15 Sep',
    notes: 'Hand sanitizers and toilet rolls packed.',
  },
  {
    id: 'fleet-4',
    name: 'VIP Mobile Restroom Trailer #2',
    type: 'vip_toilet',
    registrationOrCode: 'HLU-VIP-02',
    capacityOrSpecs: 'Dual Cubicle • Aluminium Safety Stairs • Solar Battery System',
    status: 'available',
    assignedLocation: 'Tzaneen Base Depot',
    notes: 'Deep sanitised and prepped.',
  },
  {
    id: 'fleet-5',
    name: 'Main Stage Audio Rig & 7.5kVA Gen',
    type: 'sound_system',
    registrationOrCode: 'HLU-SND-01',
    capacityOrSpecs: '2x 15" Active Tops + 2x Wireless Mics + AVR Gen',
    status: 'booked',
    assignedLocation: 'Polokwane / Mankweng',
    assignedClient: 'Mogale Community Memorial',
    bookingDates: 'Sat 14 Sep',
    notes: 'Engineer: Thabo dispatch.',
  },
  {
    id: 'fleet-6',
    name: 'Livestock Transit Utility Trailer',
    type: 'livestock_trailer',
    registrationOrCode: 'HLU-LST-01',
    capacityOrSpecs: 'High-Rail Balled Cattle & Small Stock Transport',
    status: 'available',
    assignedLocation: 'Tzaneen Base Depot',
    notes: 'Ready for livestock runs.',
  },
];

export const DEFAULT_CLIENTS: ClientRecord[] = [
  {
    id: 'cli-1',
    name: 'Phala Funeral Undertakers',
    organization: 'Phala Group',
    type: 'Funeral Parlour',
    phone: '072 411 9022',
    whatsapp: '+27724119022',
    email: 'admin@phalafunerals.co.za',
    address: 'Main Rd, Nkowankowa, Tzaneen',
    notes: 'Contract partner. Orders Cold-Room & VIP Toilet bi-weekly.',
  },
  {
    id: 'cli-2',
    name: 'Tickyline Burial Society',
    organization: 'Tickyline Community Society',
    type: 'Burial Society',
    phone: '083 992 4100',
    whatsapp: '+27839924100',
    email: 'tickyline.society@gmail.com',
    address: 'Stand 44, Tickyline Village, Lenyenye',
    notes: 'Frequent tent and sound rentals.',
  },
  {
    id: 'cli-3',
    name: 'Greater Tzaneen Protocol Unit',
    organization: 'Greater Tzaneen Municipality',
    type: 'Municipality',
    phone: '015 307 8000',
    email: 'procurement@tzaneen.gov.za',
    address: 'Agatha St, Tzaneen CBD',
    notes: 'Municipal civic and memorial setups. Requires CSD & Tax PIN.',
  },
  {
    id: 'cli-4',
    name: 'Mrs. Lerato Malatji',
    organization: 'Private Family Service',
    type: 'Family / Private',
    phone: '082 550 7819',
    whatsapp: '+27825507819',
    address: 'Dan Village, Tzaneen',
    notes: 'Weekend funeral arrangement (Cold Room, 2x Goats, VIP Toilet).',
  },
];

export const DEFAULT_RFQS: RfqLead[] = [
  {
    id: 'rfq-1',
    name: 'Samuel Baloyi',
    organization: 'Baloyi Family',
    phone: '071 884 1239',
    email: 'samuel.baloyi@gmail.com',
    serviceRequested: 'Mobile Cold-Room Trailer + VIP Toilet for 3-day funeral',
    eventDate: '2026-09-18 to 2026-09-20',
    location: 'Burgersdorp, Tzaneen',
    notes: 'Inquired on website quote form. Needs delivery Friday morning.',
    status: 'new',
    receivedAt: 'Today, 14:20',
    estimatedBudget: 7500,
  },
  {
    id: 'rfq-2',
    name: 'Grace Mokoena',
    organization: 'Mopani Events Guild',
    phone: '084 312 8790',
    email: 'grace@mopaniguild.org',
    serviceRequested: 'Stretch Tent (300 Pax) + Sound + Generator',
    eventDate: '2026-09-26',
    location: 'Giyani Multi-purpose Hall',
    notes: 'Corporate cultural symposium. Requires official written quote with CSD.',
    status: 'contacted',
    receivedAt: 'Yesterday, 16:45',
    estimatedBudget: 12000,
  },
  {
    id: 'rfq-3',
    name: 'Ebenezer Funeral Services',
    organization: 'Ebenezer Parlour Polokwane',
    phone: '082 911 3450',
    email: 'info@ebenezerfunerals.co.za',
    serviceRequested: 'Standing weekend partner rate for Limpopo mobile cold rooms',
    location: 'Polokwane / Mankweng',
    notes: 'Discussed with Thabo on WhatsApp. Quote sent.',
    status: 'quoted',
    receivedAt: '2 days ago',
  },
];

export const DEFAULT_QUOTES: QuoteDocument[] = [
  {
    id: 'q-101',
    quoteNumber: 'HLU-Q-2026-042',
    date: '2026-09-08',
    validUntil: '2026-09-22',
    clientName: 'Phala Funeral Undertakers',
    clientOrganization: 'Phala Group',
    clientPhone: '072 411 9022',
    clientEmail: 'admin@phalafunerals.co.za',
    eventLocation: 'Nkowankowa Section B, Tzaneen',
    eventDate: '2026-09-12 to 2026-09-14',
    status: 'accepted',
    items: [
      {
        id: 'item-1',
        description: 'Mobile Cold-Room Trailer (Hygienic Chiller -2°C to +4°C, Meat Rail)',
        category: 'Cold-Chain',
        quantity: 1,
        unit: 'Weekend Hire',
        unitPrice: 3500,
        total: 3500,
      },
      {
        id: 'item-2',
        description: 'VIP Mobile Restroom Trailer (Dual Private Cubicles, Porcelain Flush, Solar Lights)',
        category: 'Sanitation',
        quantity: 1,
        unit: 'Weekend Hire',
        unitPrice: 3800,
        total: 3800,
      },
      {
        id: 'item-3',
        description: 'Site Delivery, Setup & Towing Return',
        category: 'Transport',
        quantity: 1,
        unit: 'Trip',
        unitPrice: 500,
        total: 500,
      },
    ],
    subtotal: 7800,
    deliveryFee: 500,
    discount: 500,
    total: 7800,
    depositRequired: 3900,
    notes: 'Preferential partner rate applied for Phala Funeral Undertakers. 50% deposit required.',
    createdAt: '2026-09-08T10:00:00.000Z',
  },
  {
    id: 'q-102',
    quoteNumber: 'HLU-Q-2026-043',
    date: '2026-09-09',
    validUntil: '2026-09-23',
    clientName: 'Mrs. Lerato Malatji',
    clientOrganization: 'Family Memorial',
    clientPhone: '082 550 7819',
    eventLocation: 'Dan Village, Tzaneen',
    eventDate: '2026-09-13 to 2026-09-14',
    status: 'sent',
    items: [
      {
        id: 'item-1',
        description: 'VIP Mobile Restroom Trailer (Dual Cubicle, Flushable, Solar Lighting)',
        category: 'Sanitation',
        quantity: 1,
        unit: 'Weekend Hire',
        unitPrice: 3800,
        total: 3800,
      },
      {
        id: 'item-2',
        description: 'Ceremonial Livestock: Prime Indigenous Boer Goat (Slaughter Ready)',
        category: 'Livestock',
        quantity: 2,
        unit: 'Head',
        unitPrice: 2600,
        total: 5200,
      },
      {
        id: 'item-3',
        description: 'Livestock Delivery & Trailer Transit to Dan Village',
        category: 'Transport',
        quantity: 1,
        unit: 'Trip',
        unitPrice: 600,
        total: 600,
      },
    ],
    subtotal: 9600,
    deliveryFee: 600,
    discount: 0,
    total: 9600,
    depositRequired: 4800,
    notes: 'Livestock sourced from inspected Tzaneen farm holding. Delivery on Friday morning.',
    createdAt: '2026-09-09T14:30:00.000Z',
  },
];

export const DEFAULT_INVOICES: InvoiceDocument[] = [
  {
    id: 'inv-101',
    invoiceNumber: 'HLU-INV-2026-028',
    date: '2026-09-09',
    dueDate: '2026-09-12',
    quoteId: 'q-101',
    quoteNumber: 'HLU-Q-2026-042',
    clientName: 'Phala Funeral Undertakers',
    clientOrganization: 'Phala Group',
    clientPhone: '072 411 9022',
    clientEmail: 'admin@phalafunerals.co.za',
    eventLocation: 'Nkowankowa Section B, Tzaneen',
    eventDate: '2026-09-12 to 2026-09-14',
    status: 'deposit_paid',
    items: [
      {
        id: 'item-1',
        description: 'Mobile Cold-Room Trailer (Hygienic Chiller -2°C to +4°C, Meat Rail)',
        category: 'Cold-Chain',
        quantity: 1,
        unit: 'Weekend Hire',
        unitPrice: 3500,
        total: 3500,
      },
      {
        id: 'item-2',
        description: 'VIP Mobile Restroom Trailer (Dual Private Cubicles, Porcelain Flush, Solar Lights)',
        category: 'Sanitation',
        quantity: 1,
        unit: 'Weekend Hire',
        unitPrice: 3800,
        total: 3800,
      },
      {
        id: 'item-3',
        description: 'Site Delivery, Setup & Towing Return',
        category: 'Transport',
        quantity: 1,
        unit: 'Trip',
        unitPrice: 500,
        total: 500,
      },
    ],
    subtotal: 7800,
    deliveryFee: 500,
    discount: 500,
    total: 7800,
    depositPaid: 3900,
    balanceDue: 3900,
    notes: 'Deposit of R3,900 received with thanks. Balance of R3,900 payable upon Friday delivery & setup.',
    createdAt: '2026-09-09T11:00:00.000Z',
  },
];
